name: Racik Kernel NetHunter untuk SM-T285 (gtexslte) - /e/OS

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Proses Perakitan Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mulai Meracik Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: 'https://github.com/Vagr9K/kernel_samsung_gtexslte'
          kernel-branch: 'master'
          config: 'gtexslte_defconfig'
          arch: 'arm'
          aosp-gcc: true
          android-version:
          anykernel3: true
          nethunter: true
          nethunter-patch: false
          # *** BARIS INI DITAMBAHKAN ***
          extra-cmd: 'zImage'
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
